const projectUrl = 'https://ypetibqlzpzmlxvssejj.supabase.co';
const anonPublic = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZXRpYnFsenB6bWx4dnNzZWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzE1MTEsImV4cCI6MjA3MTAwNzUxMX0.At9IjVcOYk6aFn0udMv7SdMaElN3gSrhNLoS8k7jOGI';
const db = window.supabase.createClient(projectUrl, anonPublic);