name: Replace and deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Replace Placeholder
      run: |
        sed -i 's|__ANONPUBLIC__|${{ secrets.SUPABASEANONPUBLIC }}|g' script/initData.js

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
